
from diffuconpy.diffusion import diffusion_1dims
from diffuconpy.diffusion import diffusion_2dims

from diffuconpy.convection import convection_1dims
from diffuconpy.convection import convection_2dims

from diffuconpy.convection_diffusion import convection_diffusion_1dims
from diffuconpy.convection_diffusion import convection_diffusion_2dims